//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceTest.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PerformanceTest
    {
        public System.Guid Id { get; set; }
        public string T1 { get; set; }
        public Nullable<int> T2 { get; set; }
        public Nullable<decimal> T3 { get; set; }
        public Nullable<double> T4 { get; set; }
        public string T5 { get; set; }
        public System.DateTime T6 { get; set; }
        public Nullable<bool> T7 { get; set; }
        public Nullable<decimal> T8 { get; set; }
    }
}
