//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Demo.DataModel
{

    /// <summary>
    /// 实体类TStudent 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_Student")]
    [Serializable]
    public partial class TStudent : Entity
    {
        #region Model
        private Guid _Id;
        private string _Name;
        private string _IDNumber;
        private string _MobilePhone;
        private Guid? _ClassId;
        private DateTime _CreateTime;
        /// <summary>
        /// 
        /// </summary>
        public Guid Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange(_.Id, _Id, value);
                this._Id = value;
            }
        }
        /// <summary>
        /// 姓名
        /// </summary>
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange(_.Name, _Name, value);
                this._Name = value;
            }
        }
        /// <summary>
        /// 身份证号
        /// </summary>
        public string IDNumber
        {
            get { return _IDNumber; }
            set
            {
                this.OnPropertyValueChange(_.IDNumber, _IDNumber, value);
                this._IDNumber = value;
            }
        }
        /// <summary>
        /// 手机号
        /// </summary>
        public string MobilePhone
        {
            get { return _MobilePhone; }
            set
            {
                this.OnPropertyValueChange(_.MobilePhone, _MobilePhone, value);
                this._MobilePhone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public Guid? ClassId
        {
            get { return _ClassId; }
            set
            {
                this.OnPropertyValueChange(_.ClassId, _ClassId, value);
                this._ClassId = value;
            }
        }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime
        {
            get { return _CreateTime; }
            set
            {
                this.OnPropertyValueChange(_.CreateTime, _CreateTime, value);
                this._CreateTime = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.Name,
                _.IDNumber,
                _.MobilePhone,
                _.ClassId,
                _.CreateTime};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._Name,
                this._IDNumber,
                this._MobilePhone,
                this._ClassId,
                this._CreateTime};
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "T_Student");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Id = new Field("Id", "T_Student", "Id");
            /// <summary>
            /// 姓名
            /// </summary>
            public readonly static Field Name = new Field("Name", "T_Student", "姓名");
            /// <summary>
            /// 身份证号
            /// </summary>
            public readonly static Field IDNumber = new Field("IDNumber", "T_Student", "身份证号");
            /// <summary>
            /// 手机号
            /// </summary>
            public readonly static Field MobilePhone = new Field("MobilePhone", "T_Student", "手机号");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ClassId = new Field("ClassId", "T_Student", "ClassId");
            /// <summary>
            /// 创建时间
            /// </summary>
            public readonly static Field CreateTime = new Field("CreateTime", "T_Student", "创建时间");
        }
        #endregion


    }
}

