//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.CodeDom;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Dos.Model
{
    /// <summary>
    /// 实体类TPerformanceTest 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("T_PerformanceTest")]
    [Serializable]
    public partial class TPerformanceTest : Entity
    {
        #region Model
        private Guid _Id;
        private string _T1;
        private int? _T2;
        private decimal? _T3;
        private float? _T4;
        private string _T5;
        private DateTime _T6;
        private bool? _T7;
        private decimal? _T8;
        /// <summary>
        /// 
        /// </summary>
        public Guid Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string T1
        {
            get { return _T1; }
            set
            {
                this.OnPropertyValueChange("T1");
                this._T1 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? T2
        {
            get { return _T2; }
            set
            {
                this.OnPropertyValueChange("T2");
                this._T2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal? T3
        {
            get { return _T3; }
            set
            {
                this.OnPropertyValueChange("T3");
                this._T3 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public float? T4
        {
            get { return _T4; }
            set
            {
                this.OnPropertyValueChange("T4");
                this._T4 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string T5
        {
            get { return _T5; }
            set
            {
                this.OnPropertyValueChange("T5");
                this._T5 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime T6
        {
            get { return _T6; }
            set
            {
                this.OnPropertyValueChange("T6");
                this._T6 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? T7
        {
            get { return _T7; }
            set
            {
                this.OnPropertyValueChange("T7");
                this._T7 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public decimal? T8
        {
            get { return _T8; }
            set
            {
                this.OnPropertyValueChange("T8");
                this._T8 = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.T1,
                _.T2,
                _.T3,
                _.T4,
                _.T5,
                _.T6,
                _.T7,
                _.T8};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._T1,
                this._T2,
                this._T3,
                this._T4,
                this._T5,
                this._T6,
                this._T7,
                this._T8};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "T_PerformanceTest");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Id = new Field("Id", "T_PerformanceTest", "Id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field T1 = new Field("T1", "T_PerformanceTest", "T1");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field T2 = new Field("T2", "T_PerformanceTest", "T2");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field T3 = new Field("T3", "T_PerformanceTest", "T3");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field T4 = new Field("T4", "T_PerformanceTest", "T4");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field T5 = new Field("T5", "T_PerformanceTest", "T5");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field T6 = new Field("T6", "T_PerformanceTest", "T6");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field T7 = new Field("T7", "T_PerformanceTest", "T7");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field T8 = new Field("T8", "T_PerformanceTest", "T8");
        }
        #endregion


    }
}

